/** Collection + page schemas for the admin UI */

export const PAGE_SCHEMA = [
  {
    key: 'home',
    label: 'Home',
    fields: [
      { key: 'heroImage', label: 'Default hero image', type: 'image' },
      {
        key: 'heroLayout',
        label: 'Hero slider style',
        type: 'select',
        options: ['carousel', 'fade', 'split', 'spotlight', 'stack', 'aurora', 'prism', 'orbit', 'velvet', 'mosaic'],
      },
      { key: 'heroTagline', label: 'Hero tagline (above title)', type: 'text' },
      {
        key: 'howItWorksLayout',
        label: 'How It Works — section style',
        type: 'select',
        options: [
          'eclipse',
          'gatefold',
          'portals',
          'runway',
          'prism',
          'editorial',
          'compass',
          'spiral',
          'tickets',
        ],
      },
      { key: 'howItWorksTitle', label: 'How It Works — title', type: 'text' },
      { key: 'howItWorksSubtitle', label: 'How It Works — subtitle', type: 'textarea' },
      { key: 'howItWorksKicker', label: 'How It Works — kicker', type: 'text' },
      { key: 'howItWorksImage', label: 'How It Works — image', type: 'image' },
      {
        key: 'howItWorksLeftTitle',
        label: 'How It Works — left panel headline',
        type: 'text',
      },
      {
        key: 'howItWorksLeftBody',
        label: 'How It Works — left panel body',
        type: 'textarea',
      },
      {
        key: 'howItWorksRightTitle',
        label: 'How It Works — right panel headline',
        type: 'text',
      },
      {
        key: 'howItWorksRightBody',
        label: 'How It Works — right panel body',
        type: 'textarea',
      },
      {
        key: 'battleTypesLayout',
        label: 'Battle Types — section style',
        type: 'select',
        options: ['arena', 'hexpit', 'roulette', 'vhs'],
      },
      { key: 'battleTypesTitle', label: 'Battle Types — title', type: 'text' },
      { key: 'battleTypesKicker', label: 'Battle Types — kicker', type: 'text' },
      { key: 'upcomingBattlesKicker', label: 'Upcoming Battles — kicker', type: 'text' },
      { key: 'upcomingBattlesTitle', label: 'Upcoming Battles — title', type: 'text' },
      { key: 'livestreamZonesTitle', label: 'Daily Livestream Time Zones — heading', type: 'text' },
      { key: 'livestreamClockKicker', label: 'Livestream clock — kicker', type: 'text' },
      { key: 'livestreamAnchorLabel', label: 'Livestream clock — anchor label', type: 'text' },
      { key: 'livestreamClockTagline', label: 'Livestream clock — tagline', type: 'textarea' },
      {
        key: 'kmLoversLayout',
        label: 'KM Lovers — section style',
        type: 'select',
        options: ['guardian', 'shieldwall', 'beacon', 'constellation'],
      },
      { key: 'kmLoversTitle', label: 'KM Lovers — title', type: 'text' },
      { key: 'kmLoversDescription', label: 'KM Lovers — description', type: 'textarea' },
      { key: 'kmLoversPillars', label: 'KM Lovers — pillars (one per line)', type: 'textarea' },
      { key: 'kmLoversPerks', label: 'KM Lovers — perks (one per line)', type: 'textarea' },
      { key: 'kmLoversKicker', label: 'KM Lovers — kicker', type: 'text' },
      { key: 'kmLoversPerksLabel', label: 'KM Lovers — perks label', type: 'text' },
      { key: 'kmLoversImage', label: 'KM Lovers — background image', type: 'image' },
      { key: 'kmLoversFaces', label: 'KM Lovers — face avatars (comma-separated paths)', type: 'textarea' },
      {
        key: 'hostLivestreamLayout',
        label: 'Host livestream — section style',
        type: 'select',
        options: ['stage', 'broadcast', 'vault', 'premiere'],
      },
      { key: 'hostKicker', label: 'Host livestream — kicker', type: 'text' },
      { key: 'hostTitleA', label: 'Host livestream — title line 1 (outlined)', type: 'text' },
      { key: 'hostTitleB', label: 'Host livestream — title line 2', type: 'text' },
      { key: 'hostGhost', label: 'Host livestream — watermark word', type: 'text' },
      { key: 'hostImage', label: 'Host livestream — photo', type: 'image' },
      { key: 'hostCrawl', label: 'Host livestream — crawl phrases (separate with |)', type: 'text' },
      { key: 'hostPath1Chip', label: 'Host livestream — official chip', type: 'text' },
      { key: 'hostPath1Title', label: 'Host livestream — official title', type: 'text' },
      { key: 'hostPath1Body', label: 'Host livestream — official body', type: 'textarea' },
      { key: 'hostPath1Cta', label: 'Host livestream — official button', type: 'text' },
      { key: 'hostPath2Serial', label: 'Host livestream — paid serial', type: 'text' },
      { key: 'hostPath2Chip', label: 'Host livestream — paid chip', type: 'text' },
      { key: 'hostPath2Title', label: 'Host livestream — paid title', type: 'text' },
      { key: 'hostPath2Body', label: 'Host livestream — paid body', type: 'textarea' },
      { key: 'hostCurrency', label: 'Host livestream — currency symbol', type: 'text' },
      { key: 'hostPrice', label: 'Host livestream — token amount', type: 'text' },
      { key: 'hostPath2Cta', label: 'Host livestream — apply button', type: 'text' },
      { key: 'hostStubHint', label: 'Host livestream — apply hint', type: 'text' },
      { key: 'hostNameLabel', label: 'Host livestream — TikTok name label', type: 'text' },
      { key: 'hostHandleLabel', label: 'Host livestream — TikTok username label', type: 'text' },
      { key: 'hostEmailLabel', label: 'Host livestream — email label', type: 'text' },
      { key: 'hostWhatsappLabel', label: 'Host livestream — WhatsApp label', type: 'text' },
      { key: 'hostPayLabel', label: 'Host livestream — payment checkbox ({price})', type: 'text' },
      { key: 'hostSubmitLabel', label: 'Host livestream — submit button', type: 'text' },
      { key: 'hostCloseLabel', label: 'Host livestream — close button', type: 'text' },
      { key: 'hostSuccess', label: 'Host livestream — success message ({price})', type: 'textarea' },
      { key: 'hostPayError', label: 'Host livestream — unpaid error ({price})', type: 'text' },
      {
        key: 'winnersLayout',
        label: 'Winners Visit — section style',
        type: 'select',
        options: ['split', 'trophy', 'runway', 'coronation'],
      },
      { key: 'winnersTitle', label: 'Winners Visit — title', type: 'text' },
      { key: 'winnersSubtitle', label: 'Winners Visit — subtitle', type: 'textarea' },
      { key: 'winnersSteps', label: 'Winners Visit — steps (one per line)', type: 'textarea' },
      { key: 'winnersKicker', label: 'Winners Visit — kicker', type: 'text' },
      { key: 'winnersImage', label: 'Winners Visit — background image', type: 'image' },
      {
        key: 'recognitionLayout',
        label: 'Community Recognition — section style',
        type: 'select',
        options: ['marquee', 'throne', 'tapestry', 'corridor'],
      },
      { key: 'recognitionTitle', label: 'Community Recognition — title', type: 'text' },
      { key: 'recognitionKicker', label: 'Community Recognition — kicker', type: 'text' },
      { key: 'recognitionMissionTitle', label: 'Community Recognition — mission title', type: 'text' },
      { key: 'recognitionMissionBody', label: 'Community Recognition — mission body', type: 'textarea' },
      { key: 'recognitionMissionImage', label: 'Community Recognition — mission panel image', type: 'image' },
      {
        key: 'masterclassLayout',
        label: 'Masterclass Teaser — section style',
        type: 'select',
        options: ['atelier', 'ledger', 'broadcast', 'observatory'],
      },
      { key: 'masterclassTitle', label: 'Masterclass Teaser — title', type: 'text' },
      { key: 'masterclassSubtitle', label: 'Masterclass Teaser — subtitle', type: 'textarea' },
      { key: 'masterclassQuote', label: 'Masterclass Teaser — quote', type: 'textarea' },
      { key: 'masterclassKicker', label: 'Masterclass Teaser — kicker', type: 'text' },
      { key: 'masterclassFeatures', label: 'Masterclass Teaser — features (one per line)', type: 'textarea' },
      { key: 'masterclassPrice', label: 'Masterclass Teaser — price', type: 'text' },
      { key: 'masterclassDuration', label: 'Masterclass Teaser — duration', type: 'text' },
      { key: 'masterclassSchedule', label: 'Masterclass Teaser — schedule', type: 'text' },
      { key: 'masterclassInstructor', label: 'Masterclass Teaser — instructor name', type: 'text' },
      { key: 'masterclassInstructorRole', label: 'Masterclass Teaser — instructor role', type: 'text' },
      { key: 'masterclassCtaLabel', label: 'Masterclass Teaser — CTA label', type: 'text' },
      { key: 'masterclassImage', label: 'Masterclass Teaser — instructor portrait', type: 'image' },
      {
        key: 'testimonialsLayout',
        label: 'Testimonials — section style',
        type: 'select',
        options: ['spotlight', 'echo', 'scroll', 'mosaic'],
      },
      { key: 'testimonialsTitle', label: 'Testimonials — title', type: 'text' },
      { key: 'testimonialsKicker', label: 'Testimonials — kicker', type: 'text' },
      { key: 'ctaTitle', label: 'CTA — title', type: 'text' },
      { key: 'ctaSubtitle', label: 'CTA — subtitle', type: 'textarea' },
      { key: 'ctaFollowLabel', label: 'CTA — follow link label', type: 'text' },
    ],
  },
  {
    key: 'howToJoin',
    label: 'How to Join',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'heroCtaLink', label: 'Hero — secondary link text', type: 'text' },
      { key: 'gateTitle', label: 'Gate section — title', type: 'text' },
      { key: 'gateSubtitle', label: 'Gate section — subtitle', type: 'textarea' },
      { key: 'introTitle', label: 'Intro section title', type: 'text' },
      { key: 'introBody', label: 'Intro section body', type: 'textarea' },
      { key: 'ascentCtaLink', label: 'Ascent — follow link text', type: 'text' },
      { key: 'ascentCtaButton', label: 'Ascent — join button text', type: 'text' },
      { key: 'pathBKicker', label: 'Path B — kicker', type: 'text' },
      { key: 'pathBTitle', label: 'Path B — title', type: 'text' },
      { key: 'pathBBody', label: 'Path B — body', type: 'textarea' },
      { key: 'pathBButton', label: 'Path B — button text', type: 'text' },
      { key: 'pathBImage', label: 'Path B — background image', type: 'image' },
      { key: 'closingTitle', label: 'Closing section — title', type: 'text' },
      { key: 'closingBody', label: 'Closing section — body', type: 'textarea' },
      { key: 'closingImage', label: 'Closing section — background image', type: 'image' },
    ],
  },
  {
    key: 'faq',
    label: 'FAQ',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'sectionTitle', label: 'Section title below hero', type: 'text' },
      { key: 'sectionBody', label: 'Section body text', type: 'textarea' },
      { key: 'closingKicker', label: 'Closing section — kicker', type: 'text' },
      { key: 'closingTitle', label: 'Closing section — title', type: 'text' },
      { key: 'closingBody', label: 'Closing section — body', type: 'textarea' },
      { key: 'closingImage', label: 'Closing section — background image', type: 'image' },
    ],
  },
  {
    key: 'advertise',
    label: 'Advertise',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'boardKicker', label: 'Airtime board — kicker', type: 'text' },
      { key: 'boardTitle', label: 'Airtime board — title', type: 'text' },
      { key: 'boardSubtitle', label: 'Airtime board — subtitle', type: 'textarea' },
      { key: 'briefKicker', label: 'Production brief — kicker', type: 'text' },
      { key: 'briefTitle', label: 'Production brief — title', type: 'text' },
      { key: 'briefSubtitle', label: 'Production brief — subtitle', type: 'textarea' },
      { key: 'formSubmitLabel', label: 'Form — submit button text', type: 'text' },
      { key: 'formHint', label: 'Form — hint text', type: 'text' },
    ],
  },
  {
    key: 'masterclass',
    label: 'Masterclass',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'introTitle', label: 'Intro section title', type: 'text' },
      { key: 'introBody', label: 'Intro section body', type: 'textarea' },
      { key: 'curriculumTitle', label: 'Curriculum title', type: 'text' },
      { key: 'curriculumKicker', label: 'Curriculum — kicker', type: 'text' },
      { key: 'curriculumSubtitle', label: 'Curriculum — subtitle', type: 'text' },
      { key: 'tiersKicker', label: 'Tiers — kicker', type: 'text' },
      { key: 'tiersTitle', label: 'Tiers — title', type: 'text' },
      { key: 'tiersHint', label: 'Tiers — hint', type: 'text' },
      { key: 'termsKicker', label: 'Terms — kicker', type: 'text' },
      { key: 'termsTitle', label: 'Terms — title', type: 'text' },
      { key: 'termsImage', label: 'Terms — background image', type: 'image' },
      { key: 'closingKicker', label: 'Closing — kicker', type: 'text' },
      { key: 'closingTitle', label: 'Closing — title', type: 'text' },
      { key: 'closingBody', label: 'Closing — body', type: 'textarea' },
      { key: 'closingImage', label: 'Closing — background image', type: 'image' },
    ],
  },
  {
    key: 'contact',
    label: 'Contact',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Hero — title', type: 'text' },
      { key: 'heroLede', label: 'Hero — supporting line', type: 'textarea' },
      { key: 'formHeading', label: 'Form — heading', type: 'text' },
      { key: 'formSubtitle', label: 'Form — subtitle', type: 'textarea' },
      { key: 'formSubmitLabel', label: 'Form — submit button text', type: 'text' },
      {
        key: 'contactTeamLayout',
        label: 'Contact Team — section design',
        type: 'select',
        options: ['credits', 'cards', 'split', 'lineup', 'pedestal', 'polaroid', 'sigil', 'reel', 'oracle', 'broadcast', 'constellation', 'summoning'],
      },
      { key: 'teamKicker', label: 'Contact Team — kicker', type: 'text' },
      { key: 'teamTitle', label: 'Contact Team — title', type: 'text' },
      { key: 'teamSubtitle', label: 'Contact Team — subtitle', type: 'textarea' },
      { key: 'hqTitle', label: 'HQ — label', type: 'text' },
      { key: 'hqCity', label: 'HQ — city', type: 'text' },
      { key: 'hqDescription', label: 'HQ — description', type: 'textarea' },
      { key: 'hqMapUrl', label: 'HQ — map embed URL (optional)', type: 'text' },
    ],
  },
  {
    key: 'agency',
    label: 'Agency',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'introTitle', label: 'Intro / services kicker', type: 'text' },
      { key: 'introBody', label: 'Intro body (blank line = new paragraph)', type: 'textarea' },
      { key: 'scanHeading', label: 'Apply section — heading', type: 'text' },
      { key: 'scanBody', label: 'Apply section — body', type: 'textarea' },
      { key: 'criteriaText', label: 'Apply criteria (one per line)', type: 'textarea' },
      { key: 'formHeading', label: 'Application form — heading', type: 'text' },
      { key: 'formSubtitle', label: 'Application form — subtitle', type: 'textarea' },
      { key: 'formSubmitLabel', label: 'Application form — submit button', type: 'text' },
      { key: 'applyUrl', label: 'External apply URL (optional — leave blank to use on-page form)', type: 'text' },
      { key: 'qrImage', label: 'QR image override (optional)', type: 'image' },
      { key: 'servicesHeading', label: 'What We Do — heading', type: 'text' },
      { key: 'oathHeading', label: 'Closing CTA — heading', type: 'text' },
      { key: 'oathBody', label: 'Closing CTA — body', type: 'textarea' },
      { key: 'oathImage', label: 'Closing CTA — background image', type: 'image' },
    ],
  },
  {
    key: 'gallery',
    label: 'Gallery',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
    ],
  },
  {
    key: 'blog',
    label: 'Blog',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
    ],
  },
  {
    key: 'quotes',
    label: 'Daily Quotes',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'reminderKicker', label: 'Reminder — kicker', type: 'text' },
      { key: 'reminderBody', label: 'Reminder — body', type: 'textarea' },
      { key: 'meaningKicker', label: 'Quotes Meaning — kicker', type: 'text' },
      { key: 'meaningTitle', label: 'Quotes Meaning — title', type: 'text' },
      { key: 'meaningImage', label: 'Quotes Meaning — image', type: 'image' },
    ],
  },
  {
    key: 'schedule',
    label: 'Battle Schedule',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'weekHorizonKicker', label: '30-day horizon — kicker', type: 'text' },
      { key: 'weekHorizonTitle', label: '30-day horizon — title', type: 'text' },
      { key: 'finaleKicker', label: 'Finale — kicker', type: 'text' },
      { key: 'finaleTitle', label: 'Finale — title', type: 'text' },
      { key: 'finaleBody', label: 'Finale — description', type: 'textarea' },
      { key: 'finaleImage', label: 'Finale — background image', type: 'image' },
    ],
  },
  {
    key: 'outreach',
    label: 'Charity',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Headline (e.g. Your Story Matters)', type: 'text' },
      { key: 'heroSupport', label: 'Hero supporting paragraph', type: 'textarea' },
      { key: 'commitmentHeading', label: 'Our Commitment — heading', type: 'text' },
      { key: 'commitmentBody', label: 'Our Commitment — body', type: 'textarea' },
      { key: 'missionImage', label: 'Commitment — image', type: 'image' },
      { key: 'howHeading', label: 'How It Works — heading', type: 'text' },
      { key: 'formHeading', label: 'Apply form — heading', type: 'text' },
      { key: 'formSubtitle', label: 'Apply form — subtitle', type: 'textarea' },
    ],
  },
  {
    key: 'giveaway',
    label: 'Giveaway',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'vaultTitle', label: 'Claim vault — title', type: 'text' },
      { key: 'vaultSubtitle', label: 'Claim vault — subtitle', type: 'textarea' },
      { key: 'steps', label: 'How it works — steps (one per line, title: description)', type: 'textarea' },
    ],
  },
  {
    key: 'about',
    label: 'About',
    fields: [
      { key: 'heroImage', label: 'Hero image', type: 'image' },
      { key: 'heroTitle', label: 'Title', type: 'text' },
      { key: 'heroLede', label: 'Supporting line', type: 'textarea' },
      { key: 'storyTitle', label: 'Story section title', type: 'text' },
      { key: 'storyBody', label: 'Story section body', type: 'textarea' },
      { key: 'reelHeading', label: 'Reel section — heading', type: 'text' },
      { key: 'creedHeading', label: 'Creed — heading', type: 'text' },
      { key: 'castHeading', label: 'Cast — heading', type: 'text' },
      { key: 'castDescription', label: 'Cast — description', type: 'textarea' },
      { key: 'endHeading', label: 'End card — heading', type: 'text' },
      { key: 'stats', label: 'Stats ticker (one per line: value | label)', type: 'textarea' },
    ],
  },
]

export const SETTINGS_FIELDS = [
  { key: 'siteName', label: 'Site name (navbar, footer, page heroes — everywhere)', type: 'text' },
  { key: 'tagline', label: 'Tagline / Subtitle', type: 'textarea' },
  { key: 'ctaLabel', label: 'Primary CTA label', type: 'text' },
  { key: 'email', label: 'Contact email', type: 'text' },
  { key: 'phoneUS', label: 'US phone', type: 'text' },
  { key: 'phoneUG', label: 'WhatsApp / Uganda phone (shown in footer contact)', type: 'text' },
  { key: 'location', label: 'Location text (e.g. Dallas, Texas, USA)', type: 'text' },
  { key: 'copyright', label: 'Copyright text', type: 'text' },
  { key: 'disclaimer', label: 'Footer disclaimer text', type: 'text' },
  {
    key: 'footerLogoKicker',
    label: 'Text under site name (e.g. Godsent Box Battles)',
    type: 'text',
    placeholder: 'Godsent Box Battles',
  },
  { key: 'footerTiktokButton', label: 'Footer — TikTok button label', type: 'text' },
  { key: 'footerDonateButton', label: 'Footer — Donate button label', type: 'text' },
  { key: 'footerColumnExplore', label: 'Footer — Explore column title', type: 'text' },
  { key: 'footerColumnCommunity', label: 'Footer — Community column title', type: 'text' },
  { key: 'footerColumnSupport', label: 'Footer — Support column title', type: 'text' },
  { key: 'footerColumnContact', label: 'Footer — Contact column title', type: 'text' },
  { key: 'footerNewsletterTitle', label: 'Footer — newsletter title', type: 'text' },
  { key: 'footerNewsletterPlaceholder', label: 'Footer — newsletter email placeholder', type: 'text' },
  { key: 'footerNewsletterButton', label: 'Footer — newsletter button label', type: 'text' },
  { key: 'footerNewsletterSuccess', label: 'Footer — newsletter success message', type: 'text' },
  { key: 'footerSocialHeading', label: 'Footer — social heading', type: 'text' },
  { key: 'footerAdvertiseText', label: 'Footer — advertise line (before link)', type: 'text' },
  { key: 'footerAdvertiseLink', label: 'Footer — advertise link label', type: 'text' },
  { key: 'tiktokHandle', label: 'TikTok handle', type: 'text' },
  { key: 'tiktokUrl', label: 'TikTok URL', type: 'text' },
  { key: 'instagramUrl', label: 'Instagram URL', type: 'text' },
  { key: 'youtubeUrl', label: 'YouTube URL', type: 'text' },
  { key: 'threadsUrl', label: 'Threads URL', type: 'text' },
  { key: 'whatsappUrl', label: 'WhatsApp Channel URL', type: 'text' },
  { key: 'facebookUrl', label: 'Facebook URL', type: 'text' },
  { key: 'twitchUrl', label: 'Twitch URL', type: 'text' },
  { key: 'paypalEmail', label: 'PayPal business email (for donations & payments)', type: 'text' },
  {
    key: 'giftingLevelGuideVideo',
    label: 'Battle form — gifting level screenshot guide video URL (YouTube or direct video link)',
    type: 'text',
  },
]

export const COLLECTIONS = [
  {
    key: 'heroSlides',
    label: 'Hero slides',
    description: 'Homepage carousel slides',
    titleField: 'caption',
    fields: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text' },
      { key: 'caption', label: 'Caption', type: 'text' },
      { key: 'line', label: 'Supporting line', type: 'textarea' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaAction', label: 'CTA action', type: 'select', options: ['openOfficial', 'openSpecial'] },
    ],
  },
  {
    key: 'schedule',
    label: 'Battle schedule',
    description: 'Upcoming battles · use Next 30 days editor for the horizon boxes',
    titleField: 'title',
    fields: [
      { key: 'title', label: 'Battle', type: 'text' },
      { key: 'type', label: 'Type', type: 'text' },
      { key: 'date', label: 'Date (YYYY-MM-DD)', type: 'text' },
      { key: 'time', label: 'Time', type: 'text' },
      { key: 'image', label: 'Poster image (optional)', type: 'image' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'livestreamRegions',
    label: 'Livestream time zones',
    description: 'Regional livestream times on the home page',
    titleField: 'region',
    fields: [
      { key: 'region', label: 'Region name', type: 'text' },
      { key: 'time', label: 'Time (e.g. 3:30 PM)', type: 'text' },
      { key: 'abbr', label: 'Abbreviation (e.g. CST)', type: 'text' },
      { key: 'isAnchor', label: 'Anchor region (Dallas clock)', type: 'select', options: ['true', 'false'] },
      { key: 'group', label: 'Group ID (same ID = shared StatBar cell, optional)', type: 'text' },
    ],
  },
  {
    key: 'quotes',
    label: 'Daily quotes',
    description: 'Mon–Sun quote rotation',
    titleField: 'day',
    fields: [
      { key: 'day', label: 'Day', type: 'text' },
      { key: 'short', label: 'Short', type: 'text' },
      { key: 'quote', label: 'Quote', type: 'textarea' },
      { key: 'emoji', label: 'Emoji', type: 'text' },
    ],
  },
  {
    key: 'blogPosts',
    label: 'Blog posts',
    description: 'News & recaps',
    titleField: 'title',
    fields: [
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'date', label: 'Date', type: 'text' },
      { key: 'readTime', label: 'Read time', type: 'text' },
      { key: 'cover', label: 'Cover image', type: 'image' },
      { key: 'content', label: 'Content', type: 'textarea' },
    ],
  },
  {
    key: 'gallery',
    label: 'Gallery',
    description: 'Photo gallery items',
    titleField: 'title',
    fields: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'year', label: 'Year', type: 'text' },
    ],
  },
  {
    key: 'faq',
    label: 'FAQ',
    description: 'Questions & answers',
    titleField: 'question',
    fields: [
      { key: 'question', label: 'Question', type: 'text' },
      { key: 'answer', label: 'Answer', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'text' },
    ],
  },
  {
    key: 'testimonials',
    label: 'Testimonials',
    description: 'Community stories',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'handle', label: 'Handle', type: 'text' },
      { key: 'url', label: 'Profile URL', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'text', label: 'Testimonial', type: 'textarea' },
    ],
  },
  {
    key: 'topGifters',
    label: 'Top gifters',
    description: 'Community recognition',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'handle', label: 'Handle', type: 'text' },
      { key: 'url', label: 'Profile URL', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'badge', label: 'Badge', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'bio', label: 'Bio', type: 'textarea' },
    ],
  },
  {
    key: 'topFans',
    label: 'Top fans',
    description: 'Fan spotlight',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'handle', label: 'Handle', type: 'text' },
      { key: 'url', label: 'Profile URL', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'note', label: 'Note', type: 'textarea' },
    ],
  },
  {
    key: 'adPackages',
    label: 'Ad packages',
    description: 'Advertise placements',
    titleField: 'name',
    fields: [
      { key: 'code', label: 'Code', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'tag', label: 'Tag', type: 'text' },
      { key: 'availability', label: 'Availability', type: 'select', options: ['available', 'limited'] },
      { key: 'availabilityNote', label: 'Availability note', type: 'text' },
      { key: 'featuresText', label: 'Features (one per line)', type: 'textarea' },
    ],
  },
  {
    key: 'bannerAds',
    label: 'Banner ads',
    description: 'All enabled creatives rotate in a swipeable carousel at each banner zone',
    titleField: 'headline',
    fields: [
      {
        key: 'slot',
        label: 'Label / preferred zone (all enabled ads still rotate together)',
        type: 'select',
        options: [
          'home-after-upcoming',
          'home-before-testimonials',
          'schedule-after-horizon',
          'site-pre-footer',
        ],
      },
      { key: 'enabled', label: 'Enabled', type: 'select', options: ['true', 'false'] },
      { key: 'sponsorLabel', label: 'Sponsor label', type: 'text' },
      { key: 'headline', label: 'Headline', type: 'text' },
      { key: 'subline', label: 'Supporting line', type: 'textarea' },
      { key: 'ctaLabel', label: 'CTA label', type: 'text' },
      { key: 'ctaHref', label: 'CTA link (route or URL)', type: 'text' },
      { key: 'image', label: 'Creative image', type: 'image' },
      { key: 'imageAlt', label: 'Image alt text', type: 'text' },
      {
        key: 'theme',
        label: 'Theme',
        type: 'select',
        options: ['ember', 'violet', 'gold', 'ink'],
      },
      { key: 'accentColor', label: 'Accent color (optional hex)', type: 'text' },
      { key: 'bgColor', label: 'Background color (optional hex)', type: 'text' },
    ],
  },
  {
    key: 'joinSteps',
    label: 'How to Join steps',
    description: 'How to Join Box Battle steps (editable)',
    titleField: 'title',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'img', label: 'Image', type: 'image' },
    ],
  },
  {
    key: 'howItWorks',
    label: 'How it works',
    description: 'Homepage 3-step rail',
    titleField: 'title',
    fields: [
      { key: 'num', label: 'Number', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
    ],
  },
  {
    key: 'battleCatalog',
    label: 'Battle types',
    description: 'Homepage battle mosaic and signup form battle list. ID controls display order (1 = first).',
    titleField: 'title',
    editableId: true,
    fields: [
      {
        key: 'id',
        label: 'Position ID (1 = listed first)',
        type: 'number',
        placeholder: '1',
      },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'blurb', label: 'Blurb', type: 'textarea' },
      { key: 'img', label: 'Image', type: 'image' },
      {
        key: 'entryType',
        label: 'Entry type',
        type: 'select',
        options: ['official', 'special'],
      },
      {
        key: 'category',
        label: 'Category — choose Sports to show the Team field on the application form',
        type: 'select',
        options: ['General', 'Sports'],
      },
      { key: 'short', label: 'Short label (optional)', type: 'text' },
      { key: 'tag', label: 'Tag line (optional)', type: 'text' },
    ],
  },
  {
    key: 'leagueLevels',
    label: 'League levels',
    description: 'Options shown in the box battle application form',
    titleField: 'label',
    fields: [{ key: 'label', label: 'Level label (e.g. A1, B2)', type: 'text' }],
  },
  {
    key: 'masterclassTiers',
    label: 'Masterclass tiers',
    description: 'Pricing packages',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'price', label: 'Price label (display)', type: 'text' },
      { key: 'amount', label: 'Checkout amount (USD number, e.g. 500)', type: 'text' },
      { key: 'originalPrice', label: 'Original price', type: 'text' },
      { key: 'badge', label: 'Badge', type: 'text' },
      { key: 'duration', label: 'Duration', type: 'text' },
      { key: 'img', label: 'Image', type: 'image' },
      { key: 'accent', label: 'Accent color', type: 'text' },
      { key: 'short', label: 'Short label', type: 'text' },
      { key: 'featuresText', label: 'Features (one per line)', type: 'textarea' },
      { key: 'cta', label: 'CTA', type: 'text' },
    ],
  },
  {
    key: 'masterclassTerms',
    label: 'Masterclass terms',
    description: 'Program terms',
    titleField: 'text',
    fields: [{ key: 'text', label: 'Term', type: 'textarea' }],
  },
  {
    key: 'agencyRegions',
    label: 'Agency regions',
    description: 'Territory cards',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'flag', label: 'Flag emoji', type: 'text' },
      { key: 'code', label: 'Region code', type: 'text' },
      { key: 'img', label: 'Image', type: 'image' },
      { key: 'tagline', label: 'Tagline', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'benefitsText', label: 'Benefits (one per line)', type: 'textarea' },
    ],
  },
  {
    key: 'contactLines',
    label: 'Contact lines',
    description: 'Phones, email, hours (top strip + HQ links)',
    titleField: 'label',
    fields: [
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'href', label: 'Link (optional)', type: 'text' },
    ],
  },
  {
    key: 'contactTeam',
    label: 'Contact team',
    description: 'People shown on the Contact page',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'tag', label: 'Tag / handle', type: 'text' },
      { key: 'url', label: 'Profile URL', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'bio', label: 'Short bio (optional)', type: 'textarea' },
    ],
  },
  {
    key: 'aboutCast',
    label: 'About — opening credits',
    description: 'Cast shown in Opening Credits on the About page',
    titleField: 'name',
    fields: [
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'tag', label: 'Tag / handle', type: 'text' },
      { key: 'url', label: 'Profile URL', type: 'text' },
      { key: 'photo', label: 'Photo', type: 'image' },
      { key: 'bio', label: 'Short bio (optional)', type: 'textarea' },
    ],
  },
  {
    key: 'contactTopics',
    label: 'Contact form topics',
    description: 'Message topic options in the write form',
    titleField: 'title',
    fields: [
      { key: 'title', label: 'Button title', type: 'text' },
      { key: 'description', label: 'Short description', type: 'text' },
      { key: 'value', label: 'Submitted value (API topic)', type: 'text' },
    ],
  },
  {
    key: 'navLinks',
    label: 'Navbar links',
    description: 'Main navigation links',
    titleField: 'label',
    fields: [
      { key: 'to', label: 'Route (e.g. /about)', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
    ],
  },
  {
    key: 'navMoreLinks',
    label: 'Navbar "More" dropdown links',
    description: 'Secondary nav in dropdown',
    titleField: 'label',
    fields: [
      { key: 'to', label: 'Route', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
      { key: 'blurb', label: 'Short description', type: 'text' },
      { key: 'icon', label: 'Icon name', type: 'text' },
    ],
  },
  {
    key: 'footerExploreLinks',
    label: 'Footer — Explore column',
    description: 'Links in the Explore column',
    titleField: 'label',
    fields: [
      { key: 'to', label: 'Route', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
    ],
  },
  {
    key: 'footerCommunityLinks',
    label: 'Footer — Community column',
    description: 'Links in the Community column',
    titleField: 'label',
    fields: [
      { key: 'to', label: 'Route', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
    ],
  },
  {
    key: 'footerSupportLinks',
    label: 'Footer — Support column',
    description: 'Links in the Support column',
    titleField: 'label',
    fields: [
      { key: 'to', label: 'Route', type: 'text' },
      { key: 'label', label: 'Label', type: 'text' },
    ],
  },
]

export function getCollection(key) {
  return COLLECTIONS.find((c) => c.key === key)
}

export function blankItem(schema) {
  const item = { id: Date.now() }
  for (const f of schema.fields) {
    if (f.key === 'id') continue
    item[f.key] = f.type === 'select' ? f.options?.[0] || '' : ''
  }
  return item
}
